/*Ejercicio threads juego bola:
 * 1- PERMITIR MOVER LA BOLA EN LAS  CUATRO DIRECCIONES:
 * ARRIBA, IZQUERDA, DERECHA Y ABAJO
 * 
 * 2- SI LA BOLA SE SALE POR EL BORDE SUPERIOR O IZQUERDO DE LA PANTALLA,
 * INDICAR AL USUARIO QUE HA PERDIDO.
 * 
 * 3- INCLUIR UNA SERIE DE OBSTACULOS SIMILAR A LA ZONA DE META DE FORMA QUE SI LA BOLA COLISIONA CON ALGUNO D ELLOS,
 * INDICAR AL USUARIO QUE HA PERDIDO.
 * 
 * 4- UNA VEZ EL USUARIO LLEVE LA BOLA A LA ZONA DE META EN VEZ DE TERMINAR LA APLICACION,
 * PONER DE NUEVO LA BOLA EN SU POSICION INICIAL, PEDIRLE QUE LA LLEVE DE NUEVO A LA META INCREMENTANDO
 * LA VELOCIDAD DE LA BOLA.
 * 
 * 
 * OPCIONALES:
 * 
 * POSICIONAR DE FORMA ALEATORIA LOS OBSTACULOS Y LA META CADA VEZ QUE COMIENZA EL JUEGO.
 * TAMBIEN DAR UN TAMAÑO ALEATORIO A LOS MISMOS. Y FINALMENTE HACER QUE LOS OBSTACULOS SE 
 * MUEVAN SIGUIENDO UN PATRON DE MOVIMIENTO DE DERECHA -IZQUERDA ABAJO-ARRIBA.
 * 
 * NOTA: Randon r = new Random();
 * int numAleatorio = 10 + r.netInt(50);
 * 
 numAleatorio valdría un valor aleatorio entre 10 y 50 */

public class Principal {

	public static void main(String[] args) {
		new Ventana();

	}

}
